### ISSUE TITLE
generovat automaticky certifikaty pro ucastniky kurzu

### ISSUE THREAD

**Issue by jachym** [OpenGeoLabs/gismentors-registration#10]
pro účastníky kurzu vygenerovat certifiakty

- [x] rozbité místo konání
- [x] žena s (a)
- [ ] stejný e-mail přemastí původní jméno (i když se nepřihlásí)
- [x] výsledný zip s datumem a názvem kurzu
- [ ] aktualizovat šablonu
- [ ] nevypisuje se adresa v seznamu kurzů

**Comment by madlenkk** [comment]
https://github.com/OpenGeoLabs/gismentors-registration/tree/certifikates

**Comment by madlenkk** [comment]
* na větvi je rozbitý Místo konání
  * v /registration/courseevent/add/ zmizela možnost Místo konání dodatečně přidat nebo editovat (chybí ikonky + a tužka - jako jsou u typu kurzu)
  * v seznamu kurzů /courses/ se Místo konání nezobrazí - je tam jen ","

**Comment by madlenkk** [comment]
* pokud žena do přihlášky uvede titul za jménem, v certifikátu je:
  * Ing. Magdalena Kabátová Ph.D. úspěšně absolvoval
* navrhuju přistoupit na tvar absolvoval/a - je to běžné a myslím, že to ničemu nevadí - nehledě na to, že se tím vyřeší ženská jména nekončící na "á"

**Comment by madlenkk** [comment]
* Pokud se na kurz přihlásí někdo podruhé se stejným emailem, jméno v adminu se přepíše:
  * přihlásila jsem se na kurz jako A A a s emailem a@gmail.com -> OK
  * přihlásila jsem se na kurz jako B B se stejným emailem a@gmail.com -> formulář mi vyhodil: Přihláška nemohla být přijata. Uživatel s e-mailem a@gmail.com již byl na tento kurz registrován., ale v adminu se to jméno A A přepsalo na jméno B B -> mělo by tam zůstat A A

**Comment by madlenkk** [comment]
* změnit název staženého zip souboru na např.: certifikaty-2019-01-24-PostGIS

**Comment by jachym** [comment]
za mě hotovo @madlenkk

**Comment by madlenkk** [comment]
* Pokud se na kurz přihlásí někdo podruhé se stejným emailem, jméno v adminu se přepíše: (je to horší, než to bylo):
  * přihlásila jsem se na kurz jako A A a s emailem a@gmail.com -> OK
  * přihlásila jsem se na kurz jako B B se stejným emailem a@gmail.com -> přihláška byla normálně odeslána -> správně by neměla projít - formulář má vyhodit: Přihláška nemohla být přijata. Uživatel s e-mailem a@gmail.com již byl na tento kurz registrován. Zkontrolujte emailovou adresu....; V adminu se v Účastníci se to jméno účastníka A A přepsalo na jméno B B a v Účasti na kurzech je uveden dvakrát účastník B B -> měl by tam zůstat jen účastník A A
  * B B by se vůbec do databáze neměl dostat - formulář by neměl projít

**Comment by madlenkk** [comment]
hotovo
