### ISSUE TITLE
opravit zkratku FSv

### ISSUE THREAD

**Issue by landam** [OpenGeoLabs/gismentors-registration#4]
FSV ČVUT, Praha 6 -> FSv ČVUT v Praze, Praha 6

**Comment by madlenkk** [comment]
Neni to v kodu, je to v adminu - Mista konani. Opravila jsem to. Zitra vam vsem vytvorim uzivatele do adminu.

**Comment by landam** [comment]
A ten proklik na mapu?

**Comment by landam** [comment]
Nenechame issue jako enhacement?

**Comment by jachym** [comment]
Proklik na mapu ted neni hotovej, je to tam provizorne natvrdo
