### ISSUE TITLE
Registration › Účasti na kurzech 

### ISSUE THREAD

**Issue by landam** [OpenGeoLabs/gismentors-registration#8]
Pridat moznost stazeni seznamu jako CSV souboru. Vhodne v navaznosti na https://github.com/GISMentors/certifikat

**Comment by jachym** [comment]
lepší bude udělat generovátko certifikátů - je na to branch https://github.com/OpenGeoLabs/gismentors-registration/tree/certifikates

je ještě druhá branch na různý "pohledy" (json, csv) https://github.com/OpenGeoLabs/gismentors-registration/tree/views

**Comment by madlenkk** [comment]
hotovo - možnost stažení seznamu účastníků (csv) i generování certifikátů
